config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"

  get '/search', to: 'search#search'

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  attachment :profile_image, destroy: false

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :email,
      :name,
      :postcode,
      :prefecture_name,
      :address_city,
      :address_street,
      :address_building
    ])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
	def create
		current_user.follow(params[:user_id])
		redirect_to request.referer
	end

	def destroy
		current_user.unfollow(params[:user_id])
		redirect_to request.referer
	end
  def followings
		user = User.find(params[:user_id])
		@users = user.followings
  end

  def followers
		user = User.find(params[:user_id])
		@users = user.followers
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @method = params["search"]["method"]
    @records = search_for(@method, @model, @value)
  end

  private
    def match(model, value)
      if model == 'user'
        User.where(name: value)
      elsif model == 'book'
        Book.where(title: value)
      end
    end

    def forward(model, value)
      if model == 'user'
        User.where("name LIKE ?", "#{value}%")
      elsif model == 'book'
        Book.where("title LIKE ?", "#{value}%")
      end
    end

    def backward(model, value)
      if model == 'user'
        User.where("name LIKE ?", "%#{value}")
      elsif model == 'book'
        Book.where("title LIKE ?", "%#{value}")
      end
    end

    def partical(model, value)
      if model == 'user'
        User.where("name LIKE ?", "%#{value}%")
      elsif model == 'book'
        Book.where("title LIKE ?", "%#{value}%")
      end
    end

    def search_for(method, model, value)
      case method
      when 'match'
        match(model, value)
      when 'forward'
        forward(model, value)
      when 'backward'
        backward(model, value)
      when 'partical'
        partical(model, value)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body'%>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h1>Editing Book</h1>
  	<%= render 'layouts/errors', obj: @book %>
		<%= render 'form', book: @book %>
		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
		<%= link_to 'Back', books_path, class: "back" %>
    </div>
    <div class='col-md-3'></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: current_user %>

    <h2>New book</h2>
    <%= render 'form', book: @book %>
  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'index', books: @books %>
  </div>
</div>

app/views/books/show.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: @book.user %>
    <h2>New book</h2>
    <%= render 'form', book: Book.new %>
  </div>


  <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table class='table'>
		  <tr>
        <td><%= link_to user_path(@book.user) do %>
          <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
          <%= @book.user.name %>
          <% end %>
        </td>
        <td><%= link_to @book.title, book_path(@book) %></td>
        <td><%= @book.body %></td>

        <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{@book.id}"%></td>
        <% end %>
      </tr>
    </table>

  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='body'>
      <div class='container'>
        <div class="row">
          <% if user_signed_in? %>
            <%= form_with url:search_path, method: :get, local: true do |f| %>
              <%= f.text_field 'search[value]' %>
              <%= f.select 'search[model]',options_for_select({ "User" => "user", "Book" => "book" }) %>
              <%= f.select 'search[method]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
              <%= f.submit '検索' %>
            <% end %>
          <% end %>
        </div>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/search/search.html.erb
<div class="container">
  <div class="col">
    <% if @model == "user" %>
    <h2>Users search for "<%= @value %>"</h2>
    <table class="table">
        <thead>
            <tr>
              <th></th>
              <th>Name</th>
              <th>Introduction</th>
            </tr>
        </thead>
    <% @records.each do |user| %>
        <tbody>
            <tr>
                <th>
                  <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                  <%= link_to user_path(user.id) do %>
                    <%= user.name %>
                  <% end %>
                </th>
                <th>
                  <%= user.introduction %>
              </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "book" %>
    <h2>Books search for "<%= @value %>"</h2>
    <table class="table">
        <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
        </thead>
        <% @records.each do |book| %>
        <tbody>
            <tr>
                <th>
                  <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </th>
                <th>
                  <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% else %>
    <%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class='row'>

  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Users</h2>

    <%= render 'index', users: @users %>
  </div>

</div>

app/views/users/show.html.erb
<div class='row'>

  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: @user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'books/index', books: @books %>
  </div>
</div>